openapi: 3.0.0
info:
  title: PicarTsuro API
  description: SunFounder PiCar-V Tsuro API
  version: 0.0.1

servers:
  - url: /api
    description: Use IP Scanner to identify full URL

paths:
  /test:
    get:
      operationId: api_test.get_test
      tags:
        - test
      summary: Test communication
      description: Returns 200
      responses:
        '200':
          description: Success
  /info:
    get:
      operationId: api_test.get_info
      tags:
        - test
      summary: Provides application info.
      description: Returns installed packages with versions.
      responses:
        '200':
          description: A JSON array of packages and versions
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Info'
  /tsuro/start:
    get:
      operationId: api_tsuro.get_start
      tags:
        - tsuro
      summary: Launch the tsuro program
      description: Returns 200
      responses:
        '200':
          description: Success - Tsuro program started

components:
  schemas:
    Info:
      properties:
        libraries:
          type: array
        other:
          type: string
      required:  
        - libraries
