openapi: 3.0.0
info:
  title: PicarTsuro API
  description: SunFounder PiCar-V Tsuro API
  version: 0.0.1

servers:
  - url: /api
    description: Use IP Scanner to identify full URL

paths:
  /ack:
    get:
      operationId: api.get_ack
      tags:
        - dev
      summary: Test communication
      description: Returns 200
      responses:
        '200':
          description: Success
  /test_back_wheels:
    post:
      operationId: api.post_test_back_wheels
      tags:
        - dev
      summary: Test communication
      description: Returns 200
      responses:
        '200':
          description: Success
  /test_front_wheels:
    post:
      operationId: api.post_test_front_wheels
      tags:
        - dev
      summary: Test communication
      description: Returns 200
      responses:
        '200':
          description: Success
  /test_vertical_view:
    post:
      operationId: api.post_test_vertical_view
      tags:
        - dev
      summary: Test communication
      description: Returns 200
      responses:
        '200':
          description: Success
  /test_horizontal_view:
    post:
      operationId: api.post_test_horizontal_view
      tags:
        - dev
      summary: Test communication
      description: Returns 200
      responses:
        '200':
          description: Success
  /git:
    put:
      operationId: api.put_git_pull
      summary: Git pull
      description: Returns 200
      parameters:
      - name: branch_name
        in: query
        description: Name of branch to pull from
        required: true
        style: form
        explode: true
        schema:
          type: string
          default: master
          enum:
          - Dev
          - QA
          - master
      tags:
        - dev
      responses:
        '200':
          description: Success
  /info:
    get:
      operationId: api.get_info
      tags:
        - dev
      summary: Provides application info.
      description: Returns installed packages with versions.
      responses:
        '200':
          description: A JSON array of packages and versions
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Info'
  /tsuro/launch_game:
    post:
      operationId: api_tsuro.post_launch_game
      tags:
        - tsuro
      summary: Launch the tsuro program
      description: Returns 200
      responses:
        '200':
          description: Success - Tsuro program started
  /tsuro/stop:
    get:
      operationId: api_tsuro.get_stop
      tags:
        - tsuro
      summary: Stop the tsuro program
      description: Returns 200
      responses:
        '200':
          description: Success - Tsuro program stopped
  /tsuro/track_ball:
    get:
      operationId: api_tsuro.track_ball
      tags:
        - tsuro
      summary: Start the ball tracking program
      description: Returns 200
      responses:
        '200':
          description: Success - Tsuro ball tracking started
  /tsuro/track_ball_stop:
    get:
      operationId: api_tsuro.track_ball_stop
      tags:
        - tsuro
      summary: Stop the ball tracking program
      description: Returns 200
      responses:
        '200':
          description: Success - Tsuro ball tracking stopped

components:
  schemas:
    Info:
      properties:
        packages:
          type: array
        other:
          type: string

