openapi: 3.0.0
info:
  title: PicarTsuro API
  description: SunFounder PiCar-V Tsuro API
  version: 0.0.1

servers:
  - url: /api
    description: Use IP Scanner to identify full URL

paths:
  /test:
    get:
      operationId: api_test.get_test
      tags:
        - test
      summary: Test communication
      description: Returns 200
      responses:
        '200':
          description: Success
  /git:
    get:
      operationId: api_test.get_git_pull
      summary: Git pull
      description: Returns 200
      parameters:
      - name: branch_name
        in: query
        description: Name of branch to pull from
        required: true
        style: form
        explode: true
        schema:
          type: string
          default: master
          enum:
          - Dev
          - QA
          - master
      tags:
        - test
      responses:
        '200':
          description: Success
  /info:
    get:
      operationId: api_test.get_info
      tags:
        - test
      summary: Provides application info.
      description: Returns installed packages with versions.
      responses:
        '200':
          description: A JSON array of packages and versions
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Info'
  /tsuro/start:
    get:
      operationId: api_tsuro.get_start
      tags:
        - tsuro
      summary: Launch the tsuro program
      description: Returns 200
      responses:
        '200':
          description: Success - Tsuro program started
  /tsuro/stop:
    get:
      operationId: api_tsuro.get_stop
      tags:
        - tsuro
      summary: Stop the tsuro program
      description: Returns 200
      responses:
        '200':
          description: Success - Tsuro program stopped
components:
  schemas:
    Info:
      properties:
        packages:
          type: array
        other:
          type: string

